### ISSUE TITLE
Limitar CI apenas quando houver mudanças no código

### ISSUE THREAD

**Issue by endersonmaia** [turicas/covid19-br#79]
A rotina de CI (GitHub Actions) está sendo executada mesmo para commit/PR que contenham alterações de documentação (`*.md`).

O ideal seria limitar isto apenas para alterações em código que modifique comportamento do software (*.py, *.sh, Makefile, Dockerfile, ...).

**Comment by tserafim** [comment]
Se você quiser que o CI não rode quando arquivos `.md` sejam alterados:
```
  pull_request:
    paths-ignore:
    - '**.md'

  push: 
    paths-ignore:
    - '**.md'

```

Se você quiser que CI rode apenas quando `.py` e `.sh` sejam alterados:
```
  pull_request:
    paths:
    - '**.py'
    - '**.sh'

  push: 
    paths:
    - '**.py'
    - '**.sh'

```

Mais informações [aqui](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths)
